# Generated by Django 3.2.6 on 2021-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20210830_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('sports', models.CharField(max_length=50)),
                ('vacant', models.IntegerField(default=0)),
                ('required', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
